version: '3.2'                                                                                                          
                                                                                                                        
services:                                                                                                               
  web:                                                                                                                  
    build: .                                                                                                            
    restart: always                                                                                                     
    volumes:                                                                                                            
      - staticfiles:/opt/application/webapp/staticfiles                                                                 
      - ./user_management/auth_migrations:/opt/application/webapp/.venv/lib/python3.11/site-packages/django/contrib/auth/migrations
      - type: bind                                                                                                      
        source: ./media                                                                                                 
        target: /opt/application/webapp/media                                                                           
        volume:                                                                                                         
          nocopy: true                                                                                                  
    ports: # docker (8000) > gunicorn (8000)                                                                            
      - 8000                                                                                                            
    env_file:                                                                                                           
      - ./.dockerenvfile                                                                                                
    depends_on:                                                                                                         
      - db                                                                                                              
#      - redis                                                                                                          
                                                                                                                        
#  redis:                                                                                                               
#    image: 'redis:6'                                                                                                   
#    ports:                                                                                                             
#      - 6379                                                                                                           
                                                                                                                        
  db:                                                                                                                   
    image: mysql:8.0.33                                                                                                       # <Port exposed> : < MySQL Port running inside container>                                                         
    restart: always
    ports:                                                                                                             
      - 3306                                                                                                            
    #expose:                                                                                                            
      # Opens port 3306 on the container                                                                                
      #- '3306'                                                                                                         
      # Where our data will be persisted                                                                                
    volumes:                                                                                                            
      - ./my-db:/var/lib/mysql                                                                                          
    env_file:                                                                                                           
      - ./.dockerenvfile
                                                                                                                        
  nginx:                                                                                                                
    build: ./nginx                                                                                                      
    restart: always                                                                                                     
    ports: # docker (8080) > nginx (80)                                                                                 
      - 80:80                                                                                                         
    env_file:
      - ./.env
    volumes:                                                                                                            
      - staticfiles:/opt/application/webapp/staticfiles                                                                 
      - type: bind                                                                                                      
        source: ./media                                                                                                 
        target: /opt/application/webapp/media                                                                           
        volume:                                                                                                         
          nocopy: true                                                                                                  
    depends_on:                                                                                                         
      - web                                                                                                             
                                                                                                                        
# Names our volume                                                                                                      
volumes:                                                                                                                
  my-db:                                                                                                                
  staticfiles:                                                                                                          