version: 1
disable_existing_loggers: False
formatters:
  verbose:
      format: "%(asctime)s %(levelname)s %(processName)s %(threadName)s %(name)s.%(funcName)s() %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: verbose
    level: DEBUG
root:
  handlers: ['console']
  level: 'INFO'
loggers:
  django:
    handlers: ['console']
    level: DEBUG
    propagate: True
  django.request:
    handlers: ['console']
    level: DEBUG
    propagate: True
  django.server:
    handlers: ['console']
    level: WARNING
    propagate: True
  django.db.backends:
    handlers: ['console']
    level: DEBUG
    propagate: False
  django_q:
    handlers: ['console']
    level: WARNING
    propagate: False
  apps.scheduler:
    handlers: ['console']
    level: DEBUG
    propagate: False
  apps.website:
    handlers: ['console']
    level: DEBUG
    propagate: False